---
title: "GP_UHI"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load packages 
```{r}
library(rootSolve)
library(tidyverse)
library(purrr)
library(dplyr)

```


load csv 
```{r}
uhi <- read_csv("uhi_test.csv")

```

### Surface Energy Balance - Solving for surface temperature 

1. Run this code first to set the variables. 

Note: For setting the variables, we've set the initial values as the same for the parking lot example in your assignment. 

```{r vars}
T_a = 33 # ambient temp in Celsius 
alpha = 0.2 # albedo 
eps = 0.95 # emissivity 
sigma = 5.6704*10^-8 #W/m^2/K^4 stefan-boltzmann constant
k_H = 21 # sensible heat conductivity [J/deg-C]
k_E = 0 # 0 for non-wetted surface, 100 for fully wet. [J/kPa] Latent energy only present if surface is wet

RH = 0.7 # Relative humidity of atmosphere, [0-1]
RH_s = 0 # Relative humidity of the surface (assume 1 is wet/irrigated, 0 is dry)

K_inc = 750 # W/m^2, incoming shortwave radiation
#L_inc = eps * sigma * T_a^4  # W/m^2, incoming longwave radiation
Q_av = 0.9 * (K_inc*(1-alpha) + eps * sigma * T_a^4) # W/m^2 

```

2. Run this to solve for the surface temperature (with fixed values)

```{r function}
# temperature is represented as x 
fun <- function(x){ (-Q_av + eps*sigma*(x+273.15)^4 + k_H*(x-T_a) + k_E*(RH_s*0.61078*exp(17.27*x/(x+237.3)) - RH*0.61078*exp(17.27*T_a/(T_a+237.3))))

}

# solve function for temp, within the set range 
range = c(0,100)
temp_s = uniroot.all(fun, range)
temp_s


```
3. Try inputting dataframe uhi to function
```{r}
# temperature is represented as x 
fun <- function(T_a, alpha, eps, sigma, k_H, k_E, RH, RH_s, K_inc, Q_av){ (-Q_av + eps*sigma*(x+273.15)^4 + k_H*(x-T_a) + k_E*(RH_s*0.61078*exp(17.27*x/(x+237.3)) - RH*0.61078*exp(17.27*T_a/(T_a+237.3))))

}

#solve for x using uhi dataframe
solve <- function(x) pmap_dbl(uhi, fun)
uniroot.all(solve(), c(0,100))
 

```





